// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF8ci3FDO-eSrdAzHTZ3sc5HbPLkpVaU0',
    appId: '1:326383469529:web:88a4673336360f1257cfc8',
    messagingSenderId: '326383469529',
    projectId: 'healthlock-39390',
    authDomain: 'healthlock-39390.firebaseapp.com',
    storageBucket: 'healthlock-39390.firebasestorage.app',
    measurementId: 'G-J00FDLVBQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC62Icg_Ff2Y0oEExFnueI5GZs6MMVIus',
    appId: '1:326383469529:android:cb78050d70de2e2857cfc8',
    messagingSenderId: '326383469529',
    projectId: 'healthlock-39390',
    storageBucket: 'healthlock-39390.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBacrLj9fm_KxF8x5kZoIF6-8-P41ROFg',
    appId: '1:326383469529:ios:aabb3d5c254a0efd57cfc8',
    messagingSenderId: '326383469529',
    projectId: 'healthlock-39390',
    storageBucket: 'healthlock-39390.firebasestorage.app',
    iosBundleId: 'com.example.healthLock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBacrLj9fm_KxF8x5kZoIF6-8-P41ROFg',
    appId: '1:326383469529:ios:aabb3d5c254a0efd57cfc8',
    messagingSenderId: '326383469529',
    projectId: 'healthlock-39390',
    storageBucket: 'healthlock-39390.firebasestorage.app',
    iosBundleId: 'com.example.healthLock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF8ci3FDO-eSrdAzHTZ3sc5HbPLkpVaU0',
    appId: '1:326383469529:web:c2210f3dca0a9dd457cfc8',
    messagingSenderId: '326383469529',
    projectId: 'healthlock-39390',
    authDomain: 'healthlock-39390.firebaseapp.com',
    storageBucket: 'healthlock-39390.firebasestorage.app',
    measurementId: 'G-GR41RD6ZVD',
  );
}
