FROM python:3.10-slim

WORKDIR /workspace

COPY requirements.txt /workspace/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY insert_sample_data.py /workspace/insert_sample_data.py
COPY test_data/ /workspace/test_data/

CMD ["python", "insert_sample_data.py"]
